### ISSUE TITLE
画面の半分がメニュー欄に占領される

### ISSUE THREAD

**Issue by hakoniwawind** [totoraj930/TJDeck#3]
https://twitter.com/hakoniwawind/status/1059641203103133697

**Comment by totoraj930** [comment]
TweetDeck自体にサイドバー(左側に表示されている部分)をアイコンのみではなく文字まで表示する機能があります。

おそらくですがそちらの機能が有効になっていることが原因かと思われます。

下記の手順でアイコン表示のみに戻すことができますのでご確認ください。

1. TJDeck側で一番左側のカラムに移動
2. その状態で→にスワイプ(これでサイドバーがすべて表示されるかと思います)
3. サイドバーの「<< Collapse」をタップ(これでアイコンのみ表示になるかと思います)
4. ←にスワイプ(これでサイドバーが閉じます)

**Comment by hakoniwawind** [comment]
回答ありがとうございます。無事解決しました。
