### ISSUE TITLE
連続でのツイート投稿ができない

### ISSUE THREAD

**Issue by tomatogether** [totoraj930/TJDeck#4]
突然すみません。
Twitter公式アプリがあまりにも使いにくすぎるのでこちらを使わせていただいています。

今週頭あたりから、ツイートしたのちに再度ツイートをすることができなくなっていますので報告させていただきます。
一度目のツイートをしたのち、二度目のツイートをしようと投稿ボタンを押しても反応がない状態です。
環境はAndroid8.1.0です。

お手空きの際に調査・修正していただけると助かります。
よろしくお願いいたします。

**Comment by totoraj930** [comment]
昨日調査を行いましたが原因がわからず僕の力では修正不可です。

[こちら](https://gist.github.com/totoraj930/28a89735e39f423713dcd34ccc247a39)にアプリ内で読み込んでいるスクリプトのソースコードを置いてあります。

修正できるのであればこちらを修正してサーバーにホスティングして[https://github.com/totoraj930/TJDeck/blob/master/app/src/main/assets/tj-deck.js](https://github.com/totoraj930/TJDeck/blob/master/app/src/main/assets/tj-deck.js)で読み込むようにするなどしてください。

もとよりTweetDeckをAndroidで見やすく表示をいじるという性質上、TweetDeckの仕様が変われば使えなくなるものでしたので仕方ないかなと思っています。

自分が今はiPhoneをメインで使用しているのでサポートするモチベもメリットもないので、こちらのGitHubでの対応も今後するつもりもないので申し訳ないですがご了承ください。

リリースした時点でサポートなどを行わないと宣言していたものなので許してください。
